name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Reflex
      run: pip install reflex>=0.4.0

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests -p 'test_*.py'

    - name: Build the Docker image
      run: docker build -t reflex-translator-app:latest .

    - name: Run the Docker container
      run: docker run -d -p 3000:3000 -p 8000:8000 --name app reflex-translator-app:latest
